// <auto-generated />
using AlzaTechTask.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlzaTechTask.Migrations
{
    [DbContext(typeof(ProductsContext))]
    [Migration("20250130192237_SeedDatabase")]
    partial class SeedDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AlzaTechTask.Data.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("ImgUri")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "qwertyu",
                            ImgUri = "/images/productA.jpg",
                            Name = "Product A",
                            Price = 99.99m
                        },
                        new
                        {
                            Id = 2,
                            Description = "dfghjk",
                            ImgUri = "/images/productB.jpg",
                            Name = "Product B",
                            Price = 199.99m
                        },
                        new
                        {
                            Id = 3,
                            Description = "fghjkl",
                            ImgUri = "/images/productAB.jpg",
                            Name = "Product AB",
                            Price = 195.99m
                        },
                        new
                        {
                            Id = 4,
                            Description = "ertyuik",
                            ImgUri = "/images/productBA.jpg",
                            Name = "Product BA",
                            Price = 198.99m
                        },
                        new
                        {
                            Id = 5,
                            Description = "ertyuffdk",
                            ImgUri = "/images/productAA.jpg",
                            Name = "Product AA",
                            Price = 167.99m
                        },
                        new
                        {
                            Id = 6,
                            Description = "ertyccxsuik",
                            ImgUri = "/images/productBB.jpg",
                            Name = "Product BB",
                            Price = 139.99m
                        },
                        new
                        {
                            Id = 7,
                            Description = "fgjj6l",
                            ImgUri = "/images/productAC.jpg",
                            Name = "Product AC",
                            Price = 193.99m
                        },
                        new
                        {
                            Id = 8,
                            Description = "eryik",
                            ImgUri = "/images/productCA.jpg",
                            Name = "Product CA",
                            Price = 191.99m
                        },
                        new
                        {
                            Id = 9,
                            Description = "jjtyuffdk",
                            ImgUri = "/images/productCB.jpg",
                            Name = "Product CB",
                            Price = 160.99m
                        },
                        new
                        {
                            Id = 10,
                            Description = "ejjjk",
                            ImgUri = "/images/productBC.jpg",
                            Name = "Product BC",
                            Price = 135.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
