version: '3.9'
services:
  alzatechtask:
    image: alzatechtask
    build:
      context: ./AlzaTechTask
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
        - db
  db:
    image: postgres:13
    environment:
        POSTGRES_USER: yh
        POSTGRES_PASSWORD: root
        POSTGRES_DB: Products
        container_name: alzatechtask
        ports: 
          '6433:5432'
        volumes: 
          -./postgres_data:/var/lib/postgresql/data
        restart: always
  