CREATE DATABASE IF NOT EXISTS Products;
CREATE TABLE Products (
    Id INT NOT NULL PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    ImgUri VARCHAR(255) NOT NULL,
    Price DECIMAL(10, 2) NOT NULL,
    Description TEXT
);